name: "Terraform Plan"

on:
   pull_request:

jobs:
   terraform-plan:
      name: "Terraform Plan"
      runs-on: ubuntu-latest
      steps:
         - name: "Setup - Checkout"
           uses: actions/checkout@v2.1.0

         - name: "Setup - Build AWS Credentials"
           run: |
              mkdir -p ~/.aws
              echo "[default]" > ~/.aws/credentials
              echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
              echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

         - name: "Setup - Terraform CLI"
           uses: hashicorp/setup-terraform@v1.0.1

         - name: "Run - Terraform Init"
           run: terraform init -input=false

         - name: "Run - Terraform Plan"
           id: plan
           run: terraform plan -input=false -no-color

         - name: "Run - Terraform Comment"
           uses: actions/github-script@0.9.0
           env:
              STDOUT: "```${{ steps.plan.outputs.stdout }}```"
           with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                 github.issues.createComment({
                   issue_number: context.issue.number,
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   body: process.env.STDOUT
                 })
