# Name that appears when GitHub Actions run
name: "Terraform Plan"

# 1. Set to trigger on push to master
on:
   pull_request:

jobs:
   terraform-plan:
      name: "Terraform Plan"
      runs-on: ubuntu-latest
      steps:
         # 2.  Set Checkout action to checkout the code from the repo
         - name: "Setup - Checkout"
           uses: actions/checkout@v3.0.0

         # 3. Use AWS action to setup credentials
         - name: Configure AWS Credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-east-2

         # 4. Have GitHub Actions pull down the Terraform CLI from Actions registry
         - name: "Setup - Terraform CLI"
           uses: hashicorp/setup-terraform@v1.0.1

         # 5. Initialize the Terraform environment
         - name: "Run - Terraform Init"
           run: terraform init -input=false

         # 6. Run Terraform plan
         - name: "Run - Terraform Plan"
           run: terraform plan -out=tfplan -input=false -no-color
